# Site settings
title: Atlas de Conectividade | Development Seed
baseurl: "/atlas-conectividade"
url: "https://thelastenvoy.github.io"

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "sources"
    values:
      layout: "source"
  - scope:
      path: ""
      type: "themes"
    values:
      layout: "theme"

collections:
  sources:
    output: true
    permalink: /source/:path/
  themes:
    output: true
    permalink: /:path/
